const a = {
    "aspectRatio": 1.2934131736526946,
    "data": {
      "analytics": {
        "onclick": [Object],
        "onload": [Object],
        "onsent": [Object]
      },
      "analytics_response_payload": "e=Z2lmX2lkPUFlek5BS2ppNmJjbE8mZXZlbnRfdHlwZT1HSUZfVFJFTkRJTkcmY2lkPTJhYzM3MDJkbjIxNGZ6MXk2dzBsbzJ5dXRuM2FqNnhmcTh1YXUzamI2eXhxOGxjNiZjdD1n",
      "bitly_gif_url": "http://gph.is/1FdSN3b",
      "bitly_url": "http://gph.is/1FdSN3b",
      "content_url": "",
      "create_datetime": null,
      "embed_url": "https://giphy.com/embed/AezNAKji6bclO",
      "has_attribution": false,
      "id": "AezNAKji6bclO",
      "images": {
        "downsized": [Object],
        "downsized_large": [Object],
        "downsized_medium": [Object],
        "downsized_small": [Object],
        "downsized_still": [Object],
        "fixed_height": [Object],
        "fixed_height_downsampled": [Object],
        "fixed_height_small": [Object],
        "fixed_height_small_still": [Object],
        "fixed_height_still": [Object],
        "fixed_width": [Object],
        "fixed_width_downsampled": [Object],
        "fixed_width_small": [Object],
        "fixed_width_small_still": [Object],
        "fixed_width_still": [Object],
        "looping": [Object],
        "original": [Object],
        "original_still": [Object],
        "preview": [Object]
      },
      "import_datetime": "2015-03-31 14:43:14",
      "is_anonymous": false,
      "is_community": false,
      "is_dynamic": false,
      "is_featured": false,
      "is_hidden": false,
      "is_indexable": false,
      "is_preserve_size": false,
      "is_realtime": false,
      "is_removed": false,
      "is_sticker": false,
      "rating": "g",
      "slug": "good-images-pictures-AezNAKji6bclO",
      "source": "http://www.imgion.com/img/good-morning/page/2/",
      "source_post_url": "http://www.imgion.com/img/good-morning/page/2/",
      "source_tld": "www.imgion.com",
      "tags": [],
      "title": "good morning GIF by youramazing",
      "trending_datetime": "1970-01-01 00:00:00",
      "type": "gif",
      "update_datetime": null,
      "url": "https://giphy.com/gifs/good-images-pictures-AezNAKji6bclO",
      "user": undefined,
      "user_dictionary": {
        "pingbacksResponseIdKey": "n214fz1y6w0lo2yutn3aj6xfq8uau3jb6yxq8lc6"
      },
      "video": undefined
    },
    "id": "AezNAKji6bclO",
    "isDynamic": false,
    "isVideo": false,
    "url": "https://media0.giphy.com/media/AezNAKji6bclO/200w.gif?cid=2ac3702dn214fz1y6w0lo2yutn3aj6xfq8uau3jb6yxq8lc6&ep=v1_gifs_trending&rid=200w.gif&ct=g"
  }
  